### PR TITLE
Mint Sign-up Page Clone

### PR DESCRIPTION
**Pull request by Albertino2020**
In this project, I cloned the mint.com sign-up page, using HTML and CSS, in accordance with the guidelines of the second project from the Microverse's Curriculum.
Only the HTML and CSS parts were copied; thus, the links and forms go nowhere when clicked.
The overall objective of this project is to learn and practice building forms using HTML and CSS.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Albertino2020 
### Good job you have so far :clap: However, you have a few changes to work on before your project could be approved.
- Write a descriptive pull request detailing what you have done on the project, [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- Configure stickler to your project, [check this guide](https://github.com/microverseinc/linters-config/tree/master/css)
- In your html, footer tag should not be inside main tag, instead, it should be outside
footer
### [OPTIONAL]
- Practice using more of html5 semantics tag, such as main, section, article, aside etc
- Make these changes and resubmit for another code review. Good luck.
- For assistance, contact me on slack @iamraymond
- Happy coding!

**Comment by lekegitrepo** [comment]
This **PR** is under Review by: **_[TSE] Temitayo Adeleke_**

**Comment by Albertino2020** [comment]
> Hello @Albertino2020
> 
> ### Good job you have so far  However, you have a few changes to work on before your project could be approved.
> * Write a descriptive pull request detailing what you have done on the project, [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
> * Configure stickler to your project, [check this guide](https://github.com/microverseinc/linters-config/tree/master/css)
> * In your html, footer tag should not be inside main tag, instead, it should be outside
>   footer
> 
> ### [OPTIONAL]
> * Practice using more of html5 semantics tag, such as main, section, article, aside etc
> * Make these changes and resubmit for another code review. Good luck.
> * For assistance, contact me on slack @IAmRaymond
> * Happy coding!

Thank you so much, @rOluochKe!

I dd the changes and incorporated the optional changes, too.

Hope everything is OK now.

Kind regards,
Albertino

**Comment by lekegitrepo** [comment]
### Hi @Albertino2020 👍 
Excellent job so far. You have implemented:
- **_A descriptive pull request detailing what you have done on the project_**
- **_You have also improved the Html semantic of the page_**

### _But as required by the previous TSE the stickler implementation is still missing._
if the stickler is working, your pull request page should have something like this:

image

- Try to follow [this guide](https://github.com/microverseinc/linters-config/tree/master/css) as recommended by the previous reviewer.
### Note: 
Although, you have linter files in your project but make sure to enable it [here](https://stickler-ci.com/) then commit and push to be sure it's working.

**_Kindly fix this and resubmit for another review_**

### Reviewed by: _Temitayo Adeleke_

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/adeleke-temitayo-a69125188/)

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Requires Changes

**Review by nikasulo — APPROVED** [review]
# Astounding work! @Albertino2020 and @lekegitrepo :rocket: 
Congratulations, you may merge this and keep moving forward :ok_hand: I wish you all the best moving forward, and see you at the very top!

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
